---
- name: "credential: absent"
  include_role:
    name: "module"
  vars:
    # yamllint disable-line rule:line-length
    module_kind: "{{ credential_kind }}"
    # yamllint disable-line rule:line-length
    module_api_group: "{{ credential_api_group }}"
    # yamllint disable-line rule:line-length
    module_api_version: "{{ credential_api_version }}"
    # yamllint disable-line rule:line-length
    module_finalize: "{{ credential_finalize }}"
    # yamllint disable-line rule:line-length
    module_metadata_namespace: "{{ credential_metadata_namespace }}"
    # yamllint disable-line rule:line-length
    module_metadata_name: "{{ credential_metadata_name }}"
    # yamllint disable-line rule:line-length
    module_spec: "{{ credential_spec }}"
    # yamllint disable-line rule:line-length
    module_spec_collection: "{{ credential_spec_collection }}"
    # yamllint disable-line rule:line-length
    module_spec_name: "{{ credential_module_name }}"
    # yamllint disable-line rule:line-length
    module_spec_parameters: "{{ credential_spec_config }}"
    # yamllint disable-line rule:line-length
    module_spec_secret: "{{ credential_spec_secret }}"
